FROM python:3.13

USER root

WORKDIR /key.verification/

RUN apt update && apt install curl adduser -y

RUN groupadd -r helper && useradd -r -g helper bot

RUN mkdir -p /home/bot

RUN chown -R bot:helper /home/bot

COPY requirements.txt /key.verification/requirements.txt

RUN pip install -r /key.verification/requirements.txt

RUN mkdir -p /key.verification/PublicKeyStore

RUN mkdir -p /key.verification/API

COPY ./KeyVerification/* /key.verification/API/

EXPOSE 8080/tcp

CMD [ "python", "-m", "API.interface"]
