
services:
  gitserver:
    build:
      context: .
      dockerfile: Dockerfile.python
    
    image: gitforgex:1
    container_name: gitforgex
    ports:
      - protocol: TCP
        target: 8000
        published: 8000
    networks:
      gitforgex.network:
        ipv4_address: 10.0.0.22
    volumes:
      - type: volume
        source: snapshots
        target: /src/app/.git/snapshots
    env_file:
      - path: db.credentials.env
        required: true
    restart: unless-stopped
    depends_on:
      nginx.server:
        condition: service_started
      fluentd.server:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: 10.0.0.24:24224
        tag: api.server
        
  
  dbserver:
    build:
      context: .
      dockerfile: Dockerfile.clickhouse
    image: clickhouse-gitforgex:1
    container_name: clickhouse
    volumes:
      - type: bind
        source: docker-entrypoint-initdb.d/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
      - type: bind
        source: users.d/
        target: /etc/clickhouse-server/users.d/
        read_only: true
      - type: bind
        source: config.xml
        target: /etc/clickhouse-server/config.xml
        read_only: true
      - type: volume
        source: clickhouse.data
        target: /var/lib/clickhouse/
    ports:
      - protocol: TCP
        target: 9000
        published: 9000
      - protocol: TCP
        target: 8123
        published: 8123
    networks:
      gitforgex.network:
        ipv4_address: 10.0.0.21
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'select 1'"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    logging:
      driver: fluentd
      options:
        fluentd-address: 10.0.0.24:24224
        tag: db.server
        
    depends_on:
      nginx.server:
        condition: service_started
      fluentd.server:
        condition: service_healthy
      gitserver:
        condition: service_started
    restart: unless-stopped

  nginx.server:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx-gitforgex:1
    container_name: nginx
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - protocol: TCP
        target: 80
        published: 80
    logging:
      driver: fluentd
      options:
        fluentd-address: 10.0.0.24:24224
        tag: nginx.server
        
    depends_on:
      fluentd.server:
        condition: service_healthy
        
    restart: unless-stopped
  fluentd.server:
    build: 
      context: .
      dockerfile: Dockerfile.fluentd
    image: fluentd-gitforgex
    container_name: fluentd
    networks:
      gitforgex.network:
        ipv4_address: 10.0.0.24
    ports:
      - protocol: TCP
        target: 24224
        published: 24224
      - protocol: TCP
        target: 9880
        published: 9880
    volumes:
      - type: bind
        source: ./SystemLogs/api.server.logs/
        target: /fluentd/log/api/
        read_only: false

      - type: bind
        source: ./SystemLogs/db.server.logs/
        target: /fluentd/log/db/
        read_only: false

      - type: bind
        source: ./SystemLogs/nginx.server.logs/
        target: /fluentd/log/nginx/
        read_only: false

      - type: bind
        source: fluent.conf
        target: /fluentd/etc/fluent.conf
        read_only: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "24224"]
      interval: 10s
      timeout: 10s
      retries: 2
        
networks:
  gitforgex.network:
    name: gitforgex.network
    driver: bridge
    enable_ipv4: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.20

volumes:
  clickhouse.data:
  snapshots: